# 站点信息
site_name: MyWiki
site_description: MyWikiHost
site_author: Zhaoyang-Song
site_url: https://zhaoyang-song.github.io/MyWikiHost

# 右上角仓库设置
repo_url: https://github.com/Zhaoyang-Song/MyWikiHost
repo_name: Zhaoyang-Song/MyWikiHost

# 导航设置
nav:
  - Home: index.md
  - 工具:
      - CAJ转PDF: 工具/CAJ转PDF.md
      - PDF导航添加工具: 工具/PDF导航添加工具.md
  - 软件配置:
      - zotero: 软件配置/Zotero.md
      - SumatraPDF: 软件配置/SumatraPDF.md
      - vscode配置LaTeX: 软件配置/VSCode配置LaTeX.md
      - RSS: 软件配置/RSS.md
      - web: 软件配置/web.md
      - mkdocs-material: 软件配置/mkdocs-material.md


# 主题设置
theme:
  name: material  # 主题选择，现在启用material
  language: zh  # 语言
  logo: _assets/logo.svg  # logo图像设置，docs 为根目录
  favicon: _assets/logo.svg  # favicon图像设置，docs 为根目录
  icon:
    repo: fontawesome/brands/git-alt    # 右上角仓库的icon
  highlightjs: true  # 代码高亮支持，using the highlight.js JavaScript library，默认true
  hljs_style : github  # highlight.js库提供了79种不同的样式用于突出显示代码块中的源代码，默认就是github
  hljs_languages:  # 默认highlight.js只支持23个常见语言，在此处列出其他语言以包括对它们的支持 
        - yaml
        - shell

  # 字体设置
  font:
    text: Ubuntu
    code: Ubuntu Mono
  
  # 暗黑模式切换
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  
  # 一些特性
  features:
    - navigation.instant  # 即时加载，启用后将通过 XHR 拦截和分派对所有内部链接的点击，而无需完全重新加载页面
    - navigation.tracking  # 锚点跟踪，启用后地址栏中的 URL 会自动更新为目录中突出显示的活动锚点
    - navigation.tabs  # 导航标签，启用选项卡后，顶级部分呈现在上方视口标题下方的菜单层中 1220px 但在移动设备上保持原样
    # - navigation.tabs.sticky  # 顶部导航栏不会因为往下滑而不见，设置之后就是固定导航栏
    - toc.follow  # 随着文本内容移动，移动toc
    - navigation.top  # 返回顶部按钮
    - navigation.footer  # footer 上一页下一页导航启用
    - content.code.copy  # 代码复制按钮

# markdown插件
markdown_extensions:
  - pymdownx.arithmatex:  # material模板官方数学配置
      generic: true
  - pymdownx.emoji:  # emoji设置
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.betterem:  # 支持**bold**和_italic_语法
      smart_enable: all
  - toc:  # 自动从文档生成目录
      permalink: true  # 此选项添加包含段落符号的锚链接符号 
      # title: 目录 # 设置目录的title，一般可以随着语言的变化自动变化，所以这里注释掉
  - md_in_html  # 开启一些html渲染
  - def_list  # 定义列表
  - pymdownx.tasklist:  # 定义任务列表
      custom_checkbox: true  # checkbox
  # 以下功能有组合作用，为了支持高亮等格式，建议都打开
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  ####
  - footnotes  # 脚注支持
  - tables  # Markdown表格支持，正常情况下应该是默认开启的，但是为了保险起见，显式的写出来
  # 以下配置在代码块和内联代码块上启用语法高亮显示
  - pymdownx.highlight:
      linenums: true  # 全局代码添加行号
      auto_title: true  # 给代码块加一个标题，显示语言类型
  - pymdownx.inlinehilite
  - pymdownx.snippets
  ####
  # 启用对 Mermaid.js 图表支持
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  ####

# 数学公式支持，需要额外的js，现在使用的material模板官方配置
extra_javascript:
  - _javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# 插件
plugins:
  - search:
      separator: '[\s\u200b\-]'  # 中文搜索支持

# copyright
copyright: Copyright &copy; 2021 - Present | Zhaoyang Song.